version: "3"

services:
  loadbalancer:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2

  app1:
    build:
      context: .
      dockerfile: Dockerfile

  app2:
    build:
      context: .
      dockerfile: Dockerfile
